---
env:
  browser: true,
  es2021: true,
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true,
  ecmaVersion: 13
  sourceType: module

extends:
  - 'next/core-web-vitals'
  - airbnb
  - 'airbnb-hooks'
  - prettier

plugins:
  - prettier
  - react
  - '@typescript-eslint'

rules:
  arrow-body-style: 'off'
  consistent-return: 'off'
  newline-before-return: 'error'
  no-console: 'off'
  no-param-reassign: 'off'
  semi: ['error', 'never']

  import/prefer-default-export: 'off'
  import/extensions:
    - 'error'
    - 'ignorePackages'
    - ts: never
    - tsx: never

  promise/catch-or-return: 'error'

  prettier/prettier: 'warn'

  react/jsx-filename-extension: 'off'
  react/jsx-props-no-spreading: 'off'
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  react/function-component-definition:
    - 'error'
    - namedComponents: 'arrow-function'
    - unnamedComponents: 'arrow-function'

